// data.js - Inventario de ROM STORE
const products = [
    { 
        id: 21, 
        name: "SUÉTER BASIC", 
        price: 20, 
        category: ["Caballeros"], 
        onSale: false, 
        images: ["https://i.ibb.co/95WQScy/Whats-App-Image-2026-03-19-at-15-57-12.jpg", "https://i.ibb.co/r26J11Qq/Whats-App-Image-2026-03-19-at-15-57-12-1.jpg", "https://i.ibb.co/TqMhThHg/Whats-App-Image-2026-03-19-at-15-57-12-2.jpg"], 
        stock: { "Azul": ["L"], "Negro": ["M"] },
        description: "Suéter básico de diseño minimalista, ideal para un look casual o para abrigarte con estilo.",
        tags: ["sueter", "basico", "hombre", "casual", "abrigo", "streetwear"]
    },
    { 
        id: 20, 
        name: "LEGGINS GYM", 
        price: 10, 
        category: ["Damas"], 
        onSale: false, 
        images: ["https://i.ibb.co/VcPWFkLf/Whats-App-Image-2026-03-19-at-15-54-59.jpg", "https://i.ibb.co/DT9K7Wg/Whats-App-Image-2026-03-19-at-15-54-59-2.jpg"], 
        stock: { "Negro": ["Talla única"], "Marrón": ["Talla única"], "Rosado": ["Talla única"], "Azul Grisáceo": ["Talla única"], "Verde Menta": ["Talla única"] },
        description: "Leggins deportivos de alta elasticidad, perfectos para entrenamientos intensos y máxima comodidad.",
        tags: ["leggins", "gym", "mujer", "deportivo", "entrenamiento", "pantalon"]
    },
    { 
        id: 22, 
        name: "BODY FAJA HILO", 
        price: 12, 
        category: ["Damas"], 
        onSale: false, 
        images: ["https://i.ibb.co/XrjrLjSV/Whats-App-Image-2026-03-19-at-20-52-24.jpg", "https://i.ibb.co/7N0DXh7R/Whats-App-Image-2026-03-19-at-s.jpg", "https://i.ibb.co/nNVrVJD4/Whats-App-Image-2026-03-19-at-20-52-24s.jpg", "https://i.ibb.co/3mnDyBbV/Whats-App-Image-2026-03-19-at-15-58-43-3.jpg", "https://i.ibb.co/vCg1VhJK/Whats-App-Image-2026-03-19-at-15-58-43-1.jpg"], 
        stock: { "Beige": ["M"], "Negro": ["M"], "Marrón": ["M"] },
        description: "Body faja corte hilo que moldea y estiliza tu figura de forma invisible y súper cómoda bajo tu ropa.",
        tags: ["body", "faja", "hilo", "mujer", "moldeador", "basico"]
    },
    { 
        id: 23, 
        name: "LICRA PUSH UP", 
        price: 10, 
        category: ["Damas"], 
        onSale: false, 
        images: ["https://i.ibb.co/6RFwPZzh/Whats-App-Image-2026-03-19-at-16-01-17.jpg", "https://i.ibb.co/pB7vMTTZ/Whats-App-Image-2026-03-19-at-16-01-16-2.jpg", "https://i.ibb.co/fVtkb4XS/Whats-App-Image-2026-03-19-at-16-01-16-1.jpg", "https://i.ibb.co/Xfkf2LYj/Whats-App-Image-2026-03-19-at-16-01-16.jpg"], 
        stock: { "Vinotinto": ["Talla única"], "Gris claro": ["Talla única"], "Gris oscuro": ["Talla única"] },
        description: "Licra larga deportiva con tecnología push up que realza tu figura y ofrece máxima compresión.",
        tags: ["licra", "push up", "leggin", "mujer", "gym", "entrenamiento"]
    },
    { 
        id: 6, 
        name: "FRANELA NIKE DRI-FIT", 
        price: 16, 
        category: ["Caballeros"], 
        onSale: false, 
        images: ["https://i.ibb.co/NdL7ktJf/Whats-App-Image-2026-01-21-at-02-52-17.jpg","https://i.ibb.co/S4D9NmHn/Whats-App-Image-2026-01-21-at-02-52-17-1.jpg", "https://i.ibb.co/pj2P74r2/Whats-App-Image-2026-01-21-at-02-52-17-4.jpg"], 
        stock: { "Gris": ["L"], "Vinotinto": ["L"] },
        description: "Franela deportiva de alto rendimiento con tecnología de absorción de sudor DRI-FIT.",
        tags: ["nike", "camisa", "franela", "deporte", "gym", "dri-fit", "entrenamiento", "hombre"]
    },
    { 
        id: 2, 
        name: "SHORT NIKE CON LICRA", 
        price: 20, 
        category: ["Caballeros"], 
        onSale: false, 
        images: ["https://i.ibb.co/BFnDJM7/Whats-App-Image-2026-01-15-at-18-22-44-1.jpg", "https://i.ibb.co/q3NvM5ch/Whats-App-Image-2026-01-19-at-21-47-19-2.jpg"], 
        stock: { "Gris": ["L", "XL"] },
        description: "Short 2 en 1 ideal para running y levantamiento de pesas con máxima movilidad.",
        tags: ["nike", "short", "licra", "correr", "gym", "hombre"]
    },
    { 
        id: 5, 
        name: "BOXER CALVIN KLEIN", 
        price: 3.99, 
        oldPrice: 6, 
        category: ["Caballeros"], 
        onSale: true, 
        images: ["https://i.ibb.co/mVJwWHMD/Whats-App-Image-2026-01-15-at-18-22-43-1.jpg", "https://i.ibb.co/VYJgckNP/Whats-App-Image-2026-01-21-at-01-51-48.jpg"], 
        stock: { "Gris": ["XL"] },
        description: "Ropa interior cómoda, de algodón suave y diseño minimalista.",
        tags: ["ropa interior", "calvin klein", "boxer", "basico", "hombre"]
    },
    { 
        id: 7, 
        name: "TOP IMPORTADO", 
        price: 10, 
        category: ["Damas"], 
        onSale: false, 
        images: ["https://i.ibb.co/1Ghgbc9g/Whats-App-Image-2026-01-21-at-00-29-10-1.jpg", "https://i.ibb.co/bjxtCG1q/Whats-App-Image-2026-01-21-at-00-28-35-1.jpg", "https://i.ibb.co/YBjrPw1S/Whats-App-Image-2026-01-21-at-00-28-35.jpg"], 
        stock: { "Marrón": ["L", "XL"], "Azul": ["S", "M", "L"] },
        description: "Top deportivo con soporte medio, ideal para yoga o uso diario urbano.",
        tags: ["top", "mujer", "deportivo", "streetwear", "entrenamiento"]
    },
    { 
        id: 8, 
        name: "TOP BÁSICO", 
        price: 6, 
        category: ["Damas"], 
        onSale: false, 
        images: ["https://i.ibb.co/Zz7PBQQT/Whats-App-Image-2026-01-21-at-03-07-14-2.jpg", "https://i.ibb.co/LDbXLJM6/Whats-App-Image-2026-01-21-at-03-07-14-1.jpg", "https://i.ibb.co/xSKc168x/Whats-App-Image-2026-01-21-at-03-07-14.jpg", "https://i.ibb.co/B5yxL1bN/Whats-App-Image-2026-01-21-at-03-07-14-3.jpg"], 
        stock: { "Blanco": ["S", "M", "L", "XL"], "Negro": ["S", "M", "L", "XL"], "Beige": ["S", "M", "L", "XL"] },
        description: "Top esencial para cualquier outfit, altamente combinable, ligero y fresco.",
        tags: ["top", "basico", "mujer", "casual", "diario"]
    },
    { 
        id: 17, 
        name: "SHORT CON LICRA", 
        price: 20, 
        category: ["Damas"], 
        onSale: false, 
        images: ["https://i.ibb.co/Z6CyWGKC/Whats-App-Image-2026-02-12-at-21-02-22.jpg", "https://i.ibb.co/0ztnfXs/Whats-App-Image-2026-02-12-at-21-01-44.jpg"], 
        stock: { "Azul": ["S", "M"], "Negro": ["S", "M"], "Beige": ["L", "XL"], "Verde": ["L", "XL"] },
        description: "Short deportivo para mujer con licra interna para mayor seguridad y confort.",
        tags: ["short", "licra", "mujer", "gym", "entrenamiento"]
    },
    { 
        id: 18, 
        name: "LEGGIN CAMPANA", 
        price: 20, 
        category: ["Damas"], 
        onSale: false, 
        images: ["https://i.ibb.co/V0Y1CbxX/Whats-App-Image-2026-02-07-at-17-34-12.jpg", "https://i.ibb.co/chYdVL7d/Whats-App-Image-2026-02-20-at-20-07-08.jpg"], 
        stock: { "Marrón": ["L"] },
        description: "Leggin corte campana, combinando estilo urbano con comodidad deportiva.",
        tags: ["leggin", "campana", "pantalon", "mujer", "streetwear", "casual"]
    },
    { 
        id: 12, 
        name: "BIKER PUSH UP", 
        price: 4, 
        oldPrice: 8, 
        category: ["Damas"], 
        onSale: true, 
        images: ["https://i.ibb.co/hR9TnDSf/Whats-App-Image-2026-01-21-at-00-21-37.jpg"], 
        stock: { "Azul claro": ["Única"], "Morado": ["Única"] },
        description: "Biker short con efecto push up, realza la figura mientras entrenas.",
        tags: ["biker", "push up", "short", "mujer", "gym"]
    },
    { 
        id: 11, 
        name: "LICRA NIKE", 
        price: 15, 
        category: ["Damas"], 
        onSale: false, 
        images: ["https://i.ibb.co/yncw1JLj/Whats-App-Image-2026-01-21-at-02-13-29.jpg", "https://i.ibb.co/d0kT2cN9/Whats-App-Image-2026-01-21-at-02-13-29-2.jpg", "https://i.ibb.co/ZpNz9tQg/Whats-App-Image-2026-01-21-at-02-13-29-1.jpg"], 
        stock: { "Negra": ["XS", "S"], "Gris": ["XS", "S"] },
        description: "Licra deportiva Nike de alta elasticidad y transpirabilidad.",
        tags: ["nike", "licra", "leggin", "mujer", "gym", "correr"]
    },
    { 
        id: 13, 
        name: "SHORT NIKE CON LICRA", 
        price: 20, 
        category: ["Damas"], 
        onSale: false, 
        images: ["https://i.ibb.co/xtgNftS5/Whats-App-Image-2026-01-15-at-18-22-44.jpg", "https://i.ibb.co/gb6Tr38K/Whats-App-Image-2026-01-21-at-00-39-14.jpg", "https://i.ibb.co/ksCmwq6B/Whats-App-Image-2026-01-21-at-00-48-27.jpg", "https://i.ibb.co/nq7wrMCN/Whats-App-Image-2026-01-21-at-00-44-26.jpg"], 
        stock: { "Negro": ["XS", "S"], "Morado": ["S", "M"], "Beige": ["XS", "S"] },
        description: "Short Nike para damas con licra interior, confort y rendimiento.",
        tags: ["nike", "short", "licra", "mujer", "gym", "correr"]
    },
    { 
        id: 4, 
        name: "MEDIAS NIKE", 
        price: 6, 
        category: ["Caballeros", "Damas"], 
        onSale: false, 
        images: ["https://i.ibb.co/qLPqc0Y4/Whats-App-Image-2026-01-19-at-23-43-06-1.jpg", "https://i.ibb.co/7JqVv17X/Whats-App-Image-2026-01-19-at-23-43-06-2.jpg", "https://i.ibb.co/JRmz9nBq/Whats-App-Image-2026-01-19-at-23-43-06.jpg", "https://i.ibb.co/Hf7HJ70L/Whats-App-Image-2026-01-19-at-23-46-13.jpg", "https://i.ibb.co/1tfdVKvN/Whats-App-Image-2026-01-19-at-23-44-16.jpg"], 
        stock: { "Negro": ["Talla única"], "Blanco": ["Talla única"], "Gris": ["Talla única"], "Azul": ["Talla única"] },
        description: "Pack de medias de algodón transpirable, ideales para tus sneakers.",
        tags: ["nike", "medias", "calcetines", "unisex", "accesorios"]
    },
    { 
        id: 14, 
        name: "PAÑITO DE GYM ALO", 
        price: 4, 
        category: ["Damas"], 
        onSale: false, 
        images: ["https://i.ibb.co/jZzvLV1G/Whats-App-Image-2026-01-21-at-02-23-51-5.jpg", "https://i.ibb.co/HL41gYF1/Whats-App-Image-2026-01-21-at-02-23-51-1.jpg"], 
        stock: { "Gris": ["Standard"] },
        description: "Toalla compacta súper absorbente, esencial para tus rutinas.",
        tags: ["alo", "toalla", "pañito", "accesorios", "gym", "mujer"]
    },
    { 
        id: 15, 
        name: "FRANELA OVERSIZE", 
        price: 8, 
        oldPrice: 10, 
        category: ["Damas"], 
        onSale: true, 
        images: ["https://i.ibb.co/twDTh7BS/Whats-App-Image-2026-02-20-at-15-39-09.jpg", "https://i.ibb.co/Rt8xXNq/Whats-App-Image-2026-02-20-at-15-41-13.jpg"], 
        stock: { "Rosado": ["Talla Única"], "Morado": ["Talla Única"], },
        description: "Franela de corte oversize, estilo urbano y relajado.",
        tags: ["franela", "oversize", "mujer", "streetwear", "casual"]
    },
    { 
        id: 1, 
        name: "SHORT NIKE CON LICRA V1", 
        price: 20, 
        category: ["Caballeros"], 
        onSale: false, 
        outOfStock: true, 
        images: ["https://i.ibb.co/B2M1yqG9/Whats-App-Image-2026-01-21-at-01-16-51.jpg", "https://i.ibb.co/67LdJpp4/Whats-App-Image-2026-01-21-at-00-18-52.jpg", "https://i.ibb.co/4Z8BxT4d/Whats-App-Image-2026-01-21-at-00-18-52-1.jpg"], 
        stock: { "Azul": ["XL", "L"], "Gris": ["S"] },
        description: "Edición V1 del short con licra integrada. Clásico de ROM STORE.",
        tags: ["nike", "short", "licra", "gym", "agotado", "hombre"]
    },
    { 
        id: 3, 
        name: "MEDIAS ALO BLANCAS", 
        price: 3.99, 
        oldPrice: 6, 
        category: ["Caballeros", "Damas"], 
        onSale: true, 
        outOfStock: true, 
        images: ["https://i.ibb.co/67HzkgGq/Whats-App-Image-2026-01-19-at-23-50-33.jpg"], 
        stock: { "Blanco (Único)": ["Talla Única"] },
        description: "Medias de alto rendimiento con el logo clásico de Alo Yoga.",
        tags: ["alo", "medias", "calcetines", "unisex", "accesorios", "agotado"]
    },
    { 
        id: 9, 
        name: "SUDADERA DE GYM", 
        price: 16, 
        category: ["Damas"], 
        onSale: false, 
        outOfStock: true, 
        images: ["https://i.ibb.co/9kSbY03Q/Whats-App-Image-2026-01-19-at-23-27-17.jpg", "https://i.ibb.co/RGQVV7Dk/Whats-App-Image-2026-01-19-at-23-26-35.jpg"], 
        stock: { "Blanco": ["M", "L", "XL"] },
        description: "Sudadera ligera perfecta para calentar o usar post-entrenamiento.",
        tags: ["sudadera", "sueter", "mujer", "gym", "agotado"]
    },
    { 
        id: 10, 
        name: "SHORT GYMSHARK", 
        price: 10, 
        category: ["Damas"], 
        onSale: false, 
        outOfStock: true,  
        images: ["https://i.ibb.co/svB6F4JH/Whats-App-Image-2026-01-16-at-22-27-25.jpg", "https://i.ibb.co/PvQBWv0L/Whats-App-Image-2026-01-19-at-22-11-15-3.jpg"], 
        stock: { "Gris": ["Única"] },
        description: "Short seamless de alta compresión para esculpir la figura.",
        tags: ["gymshark", "short", "seamless", "mujer", "gym", "entrenamiento"],
        hidden: true
    },
    { 
        id: 19, 
        name: "BIKER PUSH UP CORTE V", 
        price: 8, 
        oldPrice: 10, 
        category: ["Damas"], 
        onSale: true, 
        outOfStock: true,   
        images: ["https://i.ibb.co/KjSfrjCy/Whats-App-Image-2026-03-12-at-14-51-41.jpg"], 
        stock: { "Azul": ["S", "M", "L"] },
        description: "Biker short push up con pretina en corte V para estilizar la cintura.",
        tags: ["biker", "push up", "corte v", "mujer", "gym", "short"]
    },
];